models/Groups.php
<?php
namespace app\models;

use app\behaviors\AliasBehavior;
use app\components\FileSaveBehavior;
use app\components\UUID;
use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "groups".
 *
 * @property integer $id
 * @property string $alias
 * @property string $name
 * @property string $uuid
 * @property int $major
 * @property int $minor
 * @property string $place
 * @property string $description
 *
 * @property BeaconBindings[] $beaconBindings
 * @property Beacons $beacons
 */
class Groups extends MainActiveRecord
{

    public $map = null;
    public static function getDropdownList() {
        $result = [];
        $models = self::find()->all();
        foreach($models as $model) {
            $result[$model->id] = $model->name;
        }
        return $result;
    }


    public function init() {
        /**@var Beacons | FileSaveBehavior $this*/
        $this->addFilesAttribute('map',GroupFiles::className(),'name',GroupFiles::TYPE_DEFAULT,'owner_id','type',
                                 '@group_save_dir','@group_view_url',null,null,'@group_view_url',function($attribute,$file_full_path,$file_path,$file_name) {
                FileHelper::createDirectory($file_path . $file_name);
                exec("convert ". $file_full_path . " -crop 256x256 -set filename:tile \"%[fx:page.x/256]-%[fx:page.y/256]\"  +repage +adjoin ".$file_path . $file_name. DIRECTORY_SEPARATOR . "tile-%[filename:tile].png");
            });

    }
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'groups';
    }
    
    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes); 
        $this->updateBeacons();
    }
    
    public function updateBeacons() {
        $beacons = $this->beacons;
        foreach($beacons as $beacon) {
            $beacon->uuid = $this->uuid;
            $beacon->save();
        } 
    } 


    public function behaviors() {
        return [
            'slug' => [
                'class' => AliasBehavior::className(),
                'in_attribute' => 'name',
                'out_attribute' => 'alias',
                'translit' => true
            ],
            'class' => FileSaveBehavior::className(),
        ];
    }

    public $is_force_uuid = false;


    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['id'], 'integer'],
            [['name', 'alias'], 'required'],
            [['name'], 'string', 'max' => 64],
            [['alias'], 'string', 'max' => 64],
            [['alias'], 'unique'],
            ['uuid', 'string', 'max' => 64],
            [['major', 'minor'], 'integer'],
            ['place', 'string', 'max' => 256],
            [['description','map'], 'safe']
        ];
    }

    public function beforeSave($insert) {
        if(parent::beforeSave($insert)) {
            if(empty($this->uuid) || $this->is_force_uuid)
                $this->uuid = UUID::v4();
            return true;
        }
        else return false;
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'alias' => Yii::t('group', ':alias'),
            'name' => Yii::t('group', ':name'),
            'description' => Yii::t('group', ':description'),
            'uuid' => Yii::t('group', ':uuid'),
            'major' => Yii::t('group', ':major'),
            'minor' => Yii::t('group', ':minor'),
            'place' => Yii::t('group', ':place'),
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBeaconBindings() {
        return $this->hasMany(BeaconBindings::className(), ['group_id' => 'id']);
    }


    public function getBeacons() {
        return $this->hasMany(Beacons::className(), ['id' => 'beacon_id'])
                    ->via('beaconBindings');
    }


    public function getUserBindings() {
        return $this->hasMany(UserBindings::className(), ['group_id' => 'id']);
    }


    public function getUsers() {
        return $this->hasMany(Users::className(), ['id' => 'user_id'])
                    ->via('userBindings');
    }


}

controllers/GroupController.php
<?php

namespace app\controllers;

use app\behaviors\AliasBehavior;
use app\commands\RbacController;
use app\components\Alert;
use app\filters\GroupLayout;
use app\filters\GroupManageLayout;
use app\models\Beacons;
use app\models\BeaconsSearch;
use app\models\Users;
use Yii;
use app\models\Groups;
use app\models\GroupSearch;
use yii\db\ActiveQuery;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\User;

/**
 * GroupController implements the CRUD actions for Groups model.
 */
class GroupController extends MainController
{
    public $defaultAction = 'list';
    public  $layout = 'main';

    public function behaviors()
    {
        $behaviors =  [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [RbacController::admin],
                    ],
                ],
            ],
            'layout' => [
                'class' => GroupLayout::className(),
                'only' => ['list','create']
            ],
            'manage-layout' => [
                'class' => GroupManageLayout::className(),
                'except' => ['list','create']
            ]
        ];

        return $behaviors;
    }


    /**
     * Lists all Groups models.
     * @return mixed
     */
    public function actionList()
    {
        $searchModel = new GroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('group-list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Groups model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('group-view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionMassDelete()
    {
        if(isset($_POST['keys']))
        {
            foreach ($_POST['keys'] as $key)
            {
                $model = $this->findModel($key);
                if($model)
                {
                    if($model->delete()){
                        Alert::addSuccess("Items has been successfully deleted");
                    }
                }
            }
        }
    }

    public function actionAsAjax($id)
    {
        $model = $this->findModel($id);
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $model->toArray();
    }


    /**
     * Creates a new Groups model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Groups();
        if($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        else
        {
            return $this->render('group-form', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Updates an existing Groups model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        else
        {
            return $this->render('group-form', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Deletes an existing Groups model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['list']);
    }


    /**
     * Finds the Groups model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Groups the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if(($model = Groups::findOne($id)) !== null)
        {
            return $model;
        }
        else
        {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionGetSelectionList()
    {
        /** @var Groups $model_class */
        $value = Yii::$app->request->getQueryParam('value');
        $query = Groups::find();
        $query->filterWhere(['like','name', $value]);
        $user = Users::getLogged(true);
        if($user->role == RbacController::user) {
            $query->joinWith(['users' => function (ActiveQuery $query) use($user) {
                $query->andFilterWhere([Users::tableName().'.id' => $user->id]);
            }]);
        }
        $models =  $query->all();
        $model_array = [];
        foreach ($models as $model)
        {
            $model_array[] =['id'=>$model->id,'text'=>  $model->name ];
        }
        echo json_encode(['more'=>false,'results'=>$model_array]);
    }


    public function actionGetSelectionById()
    {
        self::selectionById(Groups::className(),'name');
    }

    public function actionBeacons($id)
    {
        $searchModel = new BeaconsSearch();

        $searchModel->load(Yii::$app->request->queryParams);
        $dataProvider = $searchModel->search(null,$id);

        return $this->render('/beacon/beacon-list', [
            'searchModel' => new BeaconsSearch(),
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionGetAlias() {
        /**@var $model Groups |AliasBehavior*/
        $value = Yii::$app->request->getQueryParam('value');
        $model = new Groups();
        $model->name = $value;
        $model->getAlias();
        return json_encode(['success'=>true,'alias'=>$model->alias]);
    }

    public function actionCreateBeacon($id) {
        $group = $this->findModel($id);
        $model = new Beacons();
        $model->groupToBind = $group->id;
        if($model->load(Yii::$app->request->post())) {
            if($model->save())
                return $this->redirect(['beacons', 'id' => $group->id]);
        }
        return $this->render('/beacon/beacon-form', [
            'model' => $model,
            'group' => $group
        ]);
    }
}

views/group/group-form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Groups */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="groups-form">

    <br>

    <fieldset class="col-md-6">
        <legend><?php echo Yii::t('group', ':group_settings')?></legend>
        <?php $form = ActiveForm::begin([
                                            'options' => ['enctype' => 'multipart/form-data']
                                        ]); ?>

        <?= $form->field($model, 'name')->textInput() ?>
        <?= $form->field($model, 'alias')->textInput() ?>
        <?= $form->field($model, 'description')->textarea() ?>
        <?if(is_array($model->map) && count($model->map)) : ?>
            <?foreach($model->map as $file) : ?>
                <img width="200" src="<?=$model->getFileByName($file,'map')?>">
            <?endforeach?>
        <?elseif($model->map) : ?>
            <img width="200" src="<?=$model->getFile('map')?>">
        <?endif?>
        <?= $form->field($model, 'map[]')->fileInput(['multiple'=>true]) ?>
    </fieldset>
    <fieldset class="col-md-6">

        <legend><?php echo Yii::t('group', ':beacon_default_content')?></legend>
        <?= $form->field($model, 'uuid')->textInput(['maxlength' => 64]) ?>
        <?= $form->field($model, 'major')->textInput() ?>
        <?= $form->field($model, 'minor')->textInput() ?>
        <?= $form->field($model, 'place')->textInput() ?>
    </fieldset>
    <fieldset class="col-md-12">

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', ':create') : Yii::t('app', ':create'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </fieldset>

</div>
<script>
    $('#<?=Html::getInputId($model,'name')?>').on('change',function() {
        var value = $(this).prop('value');
        $.ajax({
            url : "<?=Url::to(['group/get-alias'])?>",
            type : "GET",
            dataType : "json",
            data : {
                value : value
            },
            success : function (data) {
                if(data.success) {
                    $('#<?=Html::getInputId($model,'alias')?>').prop('value',data['alias']);
                }
            }
        });
    });

</script>

views/group/group-list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Groups');
?>
<div class="groups-index">

   <br>

    <?= GridView::widget([
        'id' => 'group-list',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'layout' => "{summary}\n{pager}\n{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\CheckboxColumn'],

            [
                'attribute'=>'name',
                'format'=>'raw',
                'value'=>function($data)
                {
                    return Html::a($data->name,Url::to(['update','id'=>$data->id]));
                }
            ],
            'alias',
            'place',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php echo Html::button('Delete',['class'=>'btn btn-danger','id'=>'delete-groups'])?>
</div>
<script>
    $('#delete-groups').click(function()
    {
        if(confirm("<?=Yii::t('app','Are you sure you want to delete all selected categories?')?>"))
        {
            var list = $('#group-list').yiiGridView('getSelectedRows');
            console.log(list);
            var newlist = {};
            $(list).each(function(index,value)
            {
                newlist["keys["+index+"]"] = value;
            });
            console.log(newlist);
            $.post('<?=Url::to(['mass-delete'])?>',newlist,function(data)
            {
                window.location.reload();
            });
        }
    });
</script>

views/group/group-view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Groups */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Groups'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="groups-view">

    <br>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'alias',
            'uuid',
            'major',
            'minor',
            'place',
            'description',
        ],
    ]) ?>

</div>