controllers/SiteController.php
<?php

namespace app\controllers;

use app\commands\RbacController;
use app\components\Alert;
use app\filters\SiteLayout;
use app\models\LoginForm;
use app\models\PasswordResetForm;
use app\models\RegisterForm;
use app\models\PasswordChangeForm;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use app\models\ContactForm;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;

class SiteController extends MainController
{

    public function behaviors()
    {
         $behaviors =  array_merge(parent::behaviors(), [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'layout' => [
              'class' => SiteLayout::className(),
            ],

        ]);

        return $behaviors;

    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        if(!Yii::$app->user->isGuest) {
            if(!Yii::$app->user->can(RbacController::admin))
                return $this->redirect(['beacon/list']);
            else
                return $this->redirect(['user/list']);
        }
        $this->layout = 'landing-base-layout';
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect(Url::to('/beacon'));
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionRegister()
    {
        if(!\Yii::$app->user->isGuest)
        {
            return $this->goHome();
        }

        $model = new RegisterForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->register()) {
                if (Yii::$app->user->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionPasswordReset()
    {
        $model = new PasswordResetForm();
        if(Yii::$app->user->isGuest)
        {
            if($model->load(Yii::$app->request->post()) && $model->validate())
            {
                $model->sendEmail();
                Alert::addSuccess('Thank you. If the email address you entered matches with one that is registered in our system we will send you a reset link within the next few minutes.');
                return $this->goHome();
            }
            else
            {
                return $this->render('password-reset', [
                    'model' => $model,
                ]);
            }
        }
        else
        {
            $model->email = Yii::$app->user->identity->email;
        }
        if($model->validate())
        {
            $model->sendEmail();
            Alert::addSuccess('Thank you. If the email address you entered matches with one that is registered in our system we will send you a reset link within the next few minutes.');
            return $this->goHome();
        }
        else
        {
            return $this->render('password-reset', [
                'model' => $model,
            ]);
        }
    }





    public function actionPasswordChange($token)
    {
        try
        {
            $model = new PasswordChangeForm($token);
        }
        catch (InvalidParamException $e)
        {
            throw new BadRequestHttpException('Wrong password reset token.');
        }
        if($model->load(Yii::$app->request->post()))
        {
            if($model->validate() && $model->changePassword())
            {
                Alert::addSuccess('New password was saved.');
                return $this->goHome();
            }
            else
            {
                Alert::addError('Password hasn\'t been saved.');
                return $this->goHome();
            }
        }
        return $this->render('password-change', [
            'model' => $model,
        ]);
    }

    public function actionTerms() {
        return $this->render('terms');
    }





}

views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/**
 *
 */
use yii\helpers\Url;

?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->

    <!-- Custom CSS -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Beacon CMS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a class="page-scroll" href="<?=Url::to(['site/login'])?>">Login</a>
                </li>
                <li>
                    <a class="page-scroll" href="<?=Url::to(['promo/register'])?>">Register</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1 style="color:black">Get connected to the Beacon World!</h1>
            <hr>
            <br>
            <br>
            <a href="<?=Url::to(['promo/register'])?>" class="btn btn-primary btn-xl page-scroll">Promo register</a>
        </div>
    </div>
</header>

<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Feel free to download our application</h2>
            <a target="_blank" href="https://play.google.com/store/apps/details?id=com.kyvlabs.beaconadvertiser" class="btn btn-default btn-xl wow tada" style="background: none;"><img src="/img/android-button.png" width="200"></a>
            <a href="#" class="btn btn-default btn-xl wow tada" style="background: none;"><img src="/img/ios-button.png" width="200"></a>
        </div>
    </div>
</aside>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We've got what you need!</h2>
                <hr class="light">
                <p class="text-faded">Beacon CMS has everything you need to get your new beacon-environment up and running in no time!</p>
                <a href="<?=Url::to(['promo/register'])?>" class="btn btn-default btn-xl">Get Started!</a>
            </div>
        </div>
    </div>
</section>



<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                    <h3>Beacon management</h3>
                    <p class="text-muted">Our system allows you to easily maintain the advertisment information for your beacons</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Interactive map</h3>
                    <p class="text-muted">You can place your beacons on the interactive map</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Multilanguage support</h3>
                    <p class="text-muted">Our system could be translated in any language!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Android application</h3>
                    <p class="text-muted">We have an android application. Be always nearby your customers!</p>
                </div>
            </div>
        </div>
    </div>
</section>





<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="primary">
                <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>123-456-6789</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
            </div>
        </div>
    </div>
</section>


</body>

</html>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title =  Yii::t('general',':login');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox()->label(Yii::t('login',':remember')) ?>
    <?= Html::a(Yii::t('general',':password_forgot'),\yii\helpers\Url::to(['site/password-reset']))?>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton(Yii::t('general',':login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>


</div>

views/site/password-change.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\PasswordChangeForm */

$this->title = 'Consilium Partnership - Password Change';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container marged">
<div class="site-reset-password">
    <h1>CHANGE PASSWORD</h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            <?= $form->field($model, 'password')->passwordInput()->label(Yii::t('app','Password')) ?>
            <?= $form->field($model, 'passwordConfirm')->passwordInput()->label(Yii::t('app','Confirm password')) ?>
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
</div>

views/site/password-reset.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\PasswordResetForm */

$this->title = Yii::t('password',':password_reset');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container marged">
<div class="site-request-password-reset">
    <h1><?=Yii::t('password',':password_reset')?></h1>

    <p><?=Yii::t('password',':enter_email_address')?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email')->label(Yii::t('app',':email')) ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('app',':save'),['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
</div>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\Users */

$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to register:</p>

    <?php $form = ActiveForm::begin([
                                        'id' => 'register-form',
                                        'options' => ['class' => 'form-horizontal'],
                                        'fieldConfig' => [
                                        ],
                                    ]); ?>
    <div class="col-md-6">
    <?= $form->errorSummary($model);?>
    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'passwordConfirm')->passwordInput() ?>
    </div>

    <div class="form-group">
        <div class="col-lg-12">
            <?= Html::submitButton('Register', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/terms.php
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat magna, sollicitudin eget porta sit amet,
    ullamcorper nec nisi. Integer volutpat fermentum varius. Suspendisse elementum velit et ex commodo, sit amet
    imperdiet neque gravida. Duis accumsan id sem sed hendrerit. Donec maximus est vitae enim rutrum venenatis. Morbi
    vehicula tempor quam, vel iaculis augue tristique ac. Sed eu dolor ante. Nunc suscipit justo magna, nec ultrices
    nibh faucibus ut. Nulla convallis, est et bibendum viverra, risus augue vestibulum velit, a bibendum nibh neque vel
    ipsum.
</p>
<p>
    Nunc porttitor ac sapien sollicitudin porttitor. Suspendisse sem elit, vulputate eget lorem quis, egestas
    consectetur leo. Aliquam at varius ante, et volutpat orci. Class aptent taciti sociosqu ad litora torquent per
    conubia nostra, per inceptos himenaeos. Nulla ultricies neque felis, id imperdiet libero pulvinar non. Ut aliquet
    tempus justo ac pellentesque. Aenean lacinia, lacus sit amet efficitur consectetur, nisl mi pharetra nulla, nec
    malesuada neque nisi ac tortor. Nunc congue eget felis vitae interdum. Integer in pharetra arcu. Class aptent taciti
    sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis dignissim interdum orci, sed facilisis
    diam ornare in. Morbi egestas euismod urna, sed molestie ante bibendum vitae. Sed consectetur semper turpis a
    ultricies. Nulla ultricies sit amet arcu vel congue.
</p>
<p>
    Nulla nisi neque, finibus condimentum velit non, accumsan convallis velit. Phasellus eu justo vehicula, commodo orci
    id, fringilla est. Ut vel erat pretium, molestie magna a, auctor erat. Vivamus vitae orci ut arcu vestibulum
    vulputate. Maecenas laoreet felis sit amet tristique maximus. Aenean porttitor nisl auctor, vulputate sapien rutrum,
    elementum urna. Donec vestibulum volutpat sapien ut feugiat. Nam nec diam sed sem consectetur aliquet eget ac lacus.
    Morbi sit amet tincidunt lorem.
</p>
<p>
    Aliquam cursus velit ac risus maximus, a tincidunt neque fermentum. Aliquam ut diam lectus. Sed vel placerat nulla.
    Pellentesque rhoncus, mauris et condimentum ultricies, lorem metus pretium mauris, quis imperdiet metus sem et elit.
    Integer nec enim quis nunc volutpat tincidunt. Nullam sed justo eu odio pharetra finibus. Donec fringilla fermentum
    tempus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce euismod
    rutrum elit, vel porta lorem ultricies non. Aliquam quis malesuada turpis, bibendum viverra justo. Curabitur sit
    amet dolor fermentum, imperdiet dui sed, feugiat elit. Donec luctus, nulla et accumsan finibus, diam leo varius ex,
    non semper quam ex quis metus. Sed commodo finibus felis, ac iaculis est ultricies at. Integer at lobortis orci, ut
    dictum tortor.
</p>
<p>  Quisque egestas lacinia odio, in imperdiet ligula facilisis vitae. Mauris sed eros dolor. Cum sociis natoque
    penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam efficitur sit amet nulla ut convallis.
    Quisque et congue neque. Donec nisi metus, venenatis vitae viverra sit amet, mollis a dui. In non consequat nulla.
    Nunc felis ligula, ullamcorper id magna vel, aliquam convallis urna. Etiam congue, purus ut iaculis pellentesque,
    orci dui rhoncus est, ut vestibulum urna tortor vitae mi. Suspendisse sem ligula, semper eget elit sed, egestas
    vehicula lacus. Cras dapibus viverra fringilla. Etiam ipsum est, ultricies non finibus vitae, pharetra sit amet
    dolor. Curabitur auctor posuere odio nec venenatis.
</p>