models/ClientBeacons.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "client_beacons".
 *
 * @property integer $id
 * @property integer $client_id
 * @property integer $beacon_id
 * @property string $beaconTitle
 */
class ClientBeacons extends MainActiveRecord
{

    public function setBeaconTitle($email) {
        $this->beaconTitle = $email;
    }

    public function getBeaconTitle() {
        if(!empty($this->beaconTitle))
            return $this->beaconTitle;
        else
        {
            $beaconTitle = !empty($this->beacon) ? $this->beacon->title  : null;
            return $beaconTitle;
        }
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'client_beacons';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_id','beacon_id'],'required'],
            [['client_id', 'beacon_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'client_id' => Yii::t('app', 'Client ID'),
            'beacon_id' => Yii::t('app', 'Beacon ID'),
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(ClientUsers::className(), ['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBeacon()
    {
        return $this->hasOne(Beacons::className(), ['id' => 'beacon_id']);
    }

    public function beforeSave($insert) {
        if(parent::beforeSave($insert))
        {
            if($this->isNewRecord)
            {
                $this->created = date('Y-m-d H:i:s');
            }
            $this->updated = date('Y-m-d H:i:s');
        }
        return true;
    }
}

controllers/ClientBeaconController.php
<?php

namespace app\controllers;

use Exception;
use Yii;
use app\models\ClientBeacons;
use app\models\ClientBeaconSearch;
use app\controllers\MainController;
use console\controllers\RbacController;
use app\components\Alert;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use dosamigos\editable\EditableAction;

/**
 * ClientBeaconController implements the CRUD actions for ClientBeacons model.
 */
class ClientBeaconController extends MainController
{
    public $defaultAction = 'list';
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }

    public function actions()
    {
        return  [
            'ajax-update' => [
                'class' => EditableAction::className(),
                'modelClass' => ClientBeacons::className(),
                'forceCreate' => false
            ]
        ];
    }

    /**
     * Lists all ClientBeacons models.
     * @return mixed
     */
    public function actionList()
    {
                $searchModel = new ClientBeaconSearch();
        $searchModel->load(Yii::$app->request->queryParams);
        $dataProvider = $searchModel->search();

        return $this->render('client-beacon-list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
            }

    /**
     * Displays a single ClientBeacons model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
         $model = $this->findModel(ClientBeacons::className(),$id);
         return $this->render('client-beacon-view', [
            'model' => $model,
         ]);
    }

    /**
     * Creates a new ClientBeacons model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ClientBeacons();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('client-beacon-form', [
                   'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ClientBeacons model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(ClientBeacons::className(),$id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
                return $this->render('client-beacon-form', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ClientBeacons model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $url = Yii::$app->request->getQueryParam('url');
        try
        {
            $model = $this->findModel(ClientBeacons::className(),$id);
            $model->delete();
        }
        catch(Exception $e) {
            Alert::addError('Item has not been deleted', $e->getMessage());
        }
        return $this->redirect($url);
    }


    public function actionMassDelete()
    {
        $url = Yii::$app->request->getQueryParam('url');
        if(isset($_POST['keys']))
        {
            foreach ($_POST['keys'] as $key)
            {
                try {
                    $model = $this->findModel(ClientBeacons::className(), $key);
                    if($model)
                    {
                        if($model->delete()){
                            Alert::addSuccess("Items has been successfully deleted");
                        }
                    }
                }
                catch(Exception $e) {
                    Alert::addError('Item has not been deleted',$e->getMessage());
                }
            }
        }
        return $this->redirect($url);
    }

    public function actionAsAjax($id)
    {
        $model = $this->findModel(ClientBeacons::className(),$id);
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $model->toArray();
    }

    /**
    * Provides json response for select2 plugin
    */
    public function actionGetSelectionList()
    {
            self::selectionList(ClientBeacons::className(),'name');
    }

    /**
    * Provides json response for select2 plugin
    */
    public function actionGetSelectionById()
    {
        self::selectionById(ClientBeacons::className(),'name');
    }

}

views/client-beacon/client-beacon-form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ClientBeacons */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-beacons-form">
<br>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'client_id')->textInput() ?>

    <?= $form->field($model, 'beacon_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/client-beacon/client-beacon-list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ClientBeaconSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Client Beacons');
?>
<div class="client-beacon-index">
<br>


    <?= GridView::widget([
                             'id' => 'client-beacon-list',
                             'dataProvider' => $dataProvider,
                             'filterModel' => $searchModel,
                             'layout' => "{summary}\n{pager}\n{items}\n{pager}",
                             'columns' => [
                                 ['class' => 'yii\grid\CheckboxColumn'],

                                 'beaconTitle',
                                 [
                                     'attribute'=>'created',
                                     'format' => ['date', 'php:d-m-Y H:i:s']

                                 ],
                                 [
                                     'attribute'=>'updated',
                                     'format' => ['date', 'php:d-m-Y H:i:s']

                                 ],

                                 ['class' => 'yii\grid\ActionColumn',
                                  'controller' => 'client-beacon',
                                  'template' => '{delete}',
                                  'buttons' => [
                                      'delete' => function($url,$model,$key) {
                                          $url = Url::to(['client-beacon/delete','id'=>$model->id,'url'=> ['client-user/beacons','id'=>$_GET['id']]]);
                                          return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                              'title' => Yii::t('yii', 'Delete'),
                                              'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                              'data-method' => 'post',
                                              'data-pjax' => '0',
                                          ]);
                                      }
                                  ],
                                 ],
                             ],
                         ]); ?>
    <?php  echo Html::button('Delete',['class'=>'btn btn-danger','id'=>'delete-client-beacon'])?>

</div>
<script>
    $("#delete-client-beacon").click(function()
    {
        if(confirm("Are you sure you want to delete all selected categories?"))
        {
            var list = $('#client-beacon-list').yiiGridView('getSelectedRows');
            var newlist = {};
            $(list).each(function(index,value)
            {
                newlist["keys["+index+"]"] = value;
            });
            $.post("<?=Url::to(['client-beacon/mass-delete','url'=> ['client-user/beacons','id'=>$_GET['id']]])?>",newlist,function(data)
            {
                window.location.reload();
            });
        }
    });
</script>

views/client-beacon/client-beacon-view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ClientBeacons */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Client Beacons'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-beacons-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'client_id',
            'beacon_id',
        ],
    ]) ?>

</div>